language: node_js
node_js:
  - "6"
env:
  global:
    - secure: 4+4qAMKDoLD1BZ1ZA6JegzEuvPkl3YpjBK9b1jCa9gMOYdsN4n9bujBd2Ru2pPsxjJQ6Rm8cNd6YL1UJHOLgAc0lZwEHlcu0xhe3Dk0EajzUrM2NLd2b0a90QStWDyw5UjI9jUUwPS+mSTdWTlf2UPnesMYe/P9tNCk3wjlXCdrmA9F4ScHrX311hgt0JACNZh4MdxPZX2vgRfSG99UhooZBl9IgelUgRvu65d3gwSDYsxSBOqbJTQfOJJsfw5r6eoSDesj4aPdq5Zc8w0jFHQ1AV0631JIBPXKckC5OI+mgfyUb21abuL36vKD+HAGX/pkzG/zrLzwyEmzy5pIDVmhYXlzV/jQ36CUgCIOwjJh5iEfsidieOE4amrplZ0i0Pu5ekmhPL2PZ7sGu/xEufwhuAFvtdnsGo4YNVKnpgNBe5vSHbvfC1WL+GXvpUYB/BjeG7W10IZ+KA97NBdEno1Y06bcXtZHMMqHifDHi1b1UTbl+ZS6gRXGxwP6tOYCqeyEw4nw+uNSzOYV74ftlP+CHpNCKnqrrUpamG78bRjF73X8Pb0Wxlg4xWtywrUV7ctZ8MsceTG9ySEtRPKl2mWVm6VBmcyIQWIU7ZzQ1UwljdFS2y8Iq38g2q1Rutk8EA3YzTiSQtc/U7UaoRZ3P1ptrentnrDuvMnvyF3HGREg=
    - secure: EKBFCMw+YJdWYpzLatsWPCFViqfaVpKMv+QPx918Fyl6eO2hUfXOPVPMmC0rz8d5kEE+DYI1dNFsKA/JiXcL6k8aWHihGz6wFJORcrvvBiX5Q5pSOJV/k3UNqMurTzo9D20i1WmMc2Z/NDk+PVFOw07W7zZLEBlVQKE7G5Sz4dQ718CTmK40gVjxlGgdaQrsKVgyKOug4Xn16Izvc2p7e1JtVOLSgZLjgr1XmLGShUJK6abQc68s5VjVTNmNlUIzw2jePX9m+aZe6Pj45oW3NuxN8O8U7ZV/VsRHdeLPBzb3epimkKTjhiRizH2AEGQYF/pNNgkPs08NPVCzjWJcAqCBYkSTgohs0ZI19v795wWNM7yuvYkApULTTmruT2rA44mZPd5lbHxc6Xdn6pV7dLj+U0ORolskkXph5qNA+wOtC9DhpbhBMni6J120FnWRpdhLa4qLazIzMBFagd0/KMuU70TR+U3sePZCTLwzL9Z4oywUh1/LMMIz3oAD4/fCD4MHLoWR64wV4SDCUao+dNwVsrpP6E/GgqklmegYsIAyYKm2q4wUgR+44IvCxBuqM3o4Yr3pNrgTMBI9HN/LOO0UZ4f7+pyFsFrhhG8dxGRLyyXhcD8Wp0F8Z7ZdBOQFlXE9TfU755W08Aw5ClZSDm6D3DZ8ndhKlDDJQEdzxnI=
    - secure: WfcUXUYu9OT5oPxaLAADiOIMvHnrC4mv8KpV7QFnmUSrAkmD1BtOh935NlRqaTCIQ0dNIAh7cn7B5I6r830kCJdROEU+pz8rjX6V26sSfK4m6Tgg5W7KHrsW2qxmHSFA8PebuQ7N33q0PDu+huJGamNNrfQwjuVh+JsY7dzGosrmQJEzrx+/MVKXvPVz8uwbEQvAxbQfByM52yl+JQfKXLRP87gQr700OanBDy1LrQat4sC77Gn85GJRrDdqqGky0u+WD4oa1SxeFbW9+AfZ+ufV6lvY0KAwqLuVRZXcU48vYWpwYCCOI16zfulPN3BZmeqYZ4JD1lxZnVXnZGJ+8zDefHX1lu2NgPW4Qiy2MWjSyaxWhZBA+AZlOqlpMkQlr1NeK/HN8ZA+/XFWbHsmmICvjLNTrzyRwFT6x2LQ2O/rARjKHNa4bMmJVkghFrmq/30DPGtyH+650zSJklayzyn5ht+q8guVZRkttJ+mzCzWHtuJPyzAJvFM43QSwLaLAqaja+wv3sSfwoUTUjkrlB/b++2j/emfqEC4hkqpQG/zGRB94f2RcfErMML9EVf+pMwenXDFw9k9BUC1s5rRA/1Pq3ugVWDqw16B+A4vEzXyKgWTDEQUqF+/+ekZ1qdliCPPTDMlCMthrRvpDF1VfpCOg/EnBgC0dtnXVkXxeYw=

before_script:
  - npm install -g grunt-cli
script:
  - grunt release
deploy:
  # GitHub Releases Deployment
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file:
    - dist/zips/EMP3 Developer Guide.zip
    - dist/zips/emp3-map.zip
    - dist/zips/emp3-jsdocs.zip
    on:
      tags: true
  # GH Pages Deployment
  - provider: script
    skip_cleanup: true
    script: chmod +X ./scripts/deployGHPages.sh && ./scripts/deployGHPages.sh
    on:
      repo: missioncommand/emp3-web
      branch:
        - master
        - feature/emp3-web#90-deploy-devguide
