language: node_js
node_js:
  - "6"

before_script:
  - npm install -g grunt-cli

script:
  - grunt release

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key:
      secure: EKBFCMw+YJdWYpzLatsWPCFViqfaVpKMv+QPx918Fyl6eO2hUfXOPVPMmC0rz8d5kEE+DYI1dNFsKA/JiXcL6k8aWHihGz6wFJORcrvvBiX5Q5pSOJV/k3UNqMurTzo9D20i1WmMc2Z/NDk+PVFOw07W7zZLEBlVQKE7G5Sz4dQ718CTmK40gVjxlGgdaQrsKVgyKOug4Xn16Izvc2p7e1JtVOLSgZLjgr1XmLGShUJK6abQc68s5VjVTNmNlUIzw2jePX9m+aZe6Pj45oW3NuxN8O8U7ZV/VsRHdeLPBzb3epimkKTjhiRizH2AEGQYF/pNNgkPs08NPVCzjWJcAqCBYkSTgohs0ZI19v795wWNM7yuvYkApULTTmruT2rA44mZPd5lbHxc6Xdn6pV7dLj+U0ORolskkXph5qNA+wOtC9DhpbhBMni6J120FnWRpdhLa4qLazIzMBFagd0/KMuU70TR+U3sePZCTLwzL9Z4oywUh1/LMMIz3oAD4/fCD4MHLoWR64wV4SDCUao+dNwVsrpP6E/GgqklmegYsIAyYKm2q4wUgR+44IvCxBuqM3o4Yr3pNrgTMBI9HN/LOO0UZ4f7+pyFsFrhhG8dxGRLyyXhcD8Wp0F8Z7ZdBOQFlXE9TfU755W08Aw5ClZSDm6D3DZ8ndhKlDDJQEdzxnI=
    file:
      - "dist/zips/EMP3 Developer Guide.zip"
      - "dist/zips/emp3-map.zip"
      - "dist/zips/emp3-jsdocs.zip"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: scripts/deployGHPages.sh
    on:
      branch:
        - master
        - feature/emp3-web#90-deploy-devguide
